### ISSUE TITLE
KATO LONTE

### ISSUE THREAD

**Issue by Aijul** [KatowProject/Kato-Bot#1]
NGENTOD

**Comment by KatowProject** [comment]
lawak lo monyet

**Comment by ghost** [comment]
wah ijul bikin akun github

**Comment by Seynectheres** [comment]
p

**Comment by ikr4-m** [comment]
Lawak ni ijul

**Comment by Aijul** [comment]
![unknown (1)](https://user-images.githubusercontent.com/55964122/67144460-05ab0680-f2a9-11e9-9ac4-2895e7371633.png)
ini benar benar tidak epik

**Comment by ghost** [comment]
woy ini github, goblok

**Comment by ghost** [comment]
close aja issue-nya @KatowProject
