### ISSUE TITLE
[Feature Request] Remove Reaction when Someone Leave Server.

### ISSUE THREAD

**Issue by ghost** [KatowProject/Kato-Bot#3]
Jadi, kalo ada seseorang yang leave server dan udah ngambil role `Santai`, pas masuk kembali ke server yang ditinggalnya, reaction di message Kato-Bot masih ada, tapi role Santai-nya gak ada, dan kalo mau ngambil kembali role Santai-nya, harus unreact terlebih dahulu lalu react kembali.

Request:
Biar gak unreact lalu react kembali, tolong tambahkan fitur dimana ketika seseorang keluar dari server, maka di react di message Kato-Bot hilang secara otomatis.

**Comment by KatowProject** [comment]
Terima Kasih atas sarannya,
nanti aku cari caranya biar suatu member out /leave itu 
reactnya langsung ilang

**Comment by ghost** [comment]
kali aja dapet pencerahan pas baca [dokumentasi ini](https://discord.js.org/#/docs/main/stable/search?q=reaction).

**Comment by MzHellcat** [comment]
kan reactionnya pake bot yui
jadi bukan masalah di bot si naufal itu
