### ISSUE TITLE
Download Kusonime

### ISSUE THREAD

**Issue by NiuEr1** [KatowProject/Kato-Bot#37]
What happen i get "Request failed with status code 504" ?

**Comment by KatowProject** [comment]
504 means a bad request.
check your connection or cloudflare blocking your ip.

if still same problem, i will change the website request

thank you

**Comment by NiuEr1** [comment]
> 504 means a bad request.
> check your connection or cloudflare blocking your ip.
> 
> if still same problem, i will change the website request
> 
> thank you

But another commands work normally, just Kusonime get error "code 504" and i try run on localhost via cmd, i found this 
https://cdn.discordapp.com/attachments/739044939672977428/862257094128042004/unknown.png

**Comment by KatowProject** [comment]
fixed it
